/*
 * Generated by erpcgen 1.9.0 on Tue May 31 17:37:32 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_bbcar_control_h_)
#define _bbcar_control_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief BBCarService identifiers */
enum _BBCarService_ids
{
    kBBCarService_service_id = 1,
    kBBCarService_returndistance_id = 1,
    kBBCarService_returnspeed_id = 2,
    kBBCarService_returnstatus_id = 3,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name BBCarService
//@{
void returndistance(float * result);

void returnspeed(float * result);

void returnstatus(float * result);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _bbcar_control_h_
