#
# Generated by erpcgen 1.9.0 on Tue May 31 17:37:31 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for BBCarService
class IBBCarService(object):
    SERVICE_ID = 1
    RETURNDISTANCE_ID = 1
    RETURNSPEED_ID = 2
    RETURNSTATUS_ID = 3

    def returndistance(self, result):
        raise NotImplementedError()

    def returnspeed(self, result):
        raise NotImplementedError()

    def returnstatus(self, result):
        raise NotImplementedError()


